export BUILD=20231109
cd /home/android/lineage/out/target/product/gtexslte/
rm *.tar
rm *.zip
tar -H ustar -c boot.img system.img > LINEAGE-OMS-14.1-$BUILD-UNOFFICIAL-SMT285-ALPHA.tar && \
md5sum -t LINEAGE-OMS-14.1-$BUILD-UNOFFICIAL-SMT285-ALPHA.tar >> LINEAGE-OMS-14.1-$BUILD-UNOFFICIAL-SMT285-ALPHA.tar && \
mv LINEAGE-OMS-14.1-$BUILD-UNOFFICIAL-SMT285-ALPHA.tar LINEAGE-OMS-14.1-$BUILD-UNOFFICIAL-SMT285-ALPHA.tar.md5 && \
gzip -c LINEAGE-OMS-14.1-$BUILD-UNOFFICIAL-SMT285-ALPHA.tar.md5 > LINEAGE-OMS-14.1-$BUILD-UNOFFICIAL-SMT285-ALPHA.zip